exemple : testMethodeTaquin.pdf ensembleincomplettest.pdf Diagramme\ de\ GANTT.pdf
	pdfcrop --margins '-40 -40 -80 -400' testMethodeTaquin.pdf testMethodeTaquin2.pdf
	pdfcrop --margins '-40 -40 -80 -400' ensembleincomplettest.pdf ensembleincomplettest2.pdf
	pdfcrop --margins '0 -10 0 -470' Diagramme\ de\ GANTT.pdf DiagrammeDeGantt.pdf

